version: '3.9'
name: 'comp-dist'

services:
  rust-app:
    container_name: rust-app
    build: ./rs
    ports:
      - "8000:8000"
  kt-app:
    container_name: kt-app
    build: ./kt
    ports:
      - "8080:8080"
  